CREATE DATABASE SignUp_DB;

CREATE TABLE tbl_SignUp
(
Id INT PRIMARY KEY IDENTITY(1,1),
FullName VARCHAR(20),
Email VARCHAR(30),
Phone VARCHAR(13),
UserName VARCHAR(15),
Password VARCHAR(20)

)